# Generated by Django 4.2.27 on 2026-01-29 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandal_code', models.CharField(max_length=20, unique=True)),
                ('mandal_name', models.CharField(max_length=150)),
                ('local_name', models.CharField(blank=True, max_length=150)),
                ('is_municipality', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_code', models.CharField(max_length=20, unique=True)),
                ('division_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('step_number', models.IntegerField()),
                ('total_steps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mobile_number', models.CharField(db_index=True, help_text='10-digit mobile number of the respondent', max_length=15, unique=True)),
                ('is_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.revenuedivision')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mandal')),
            ],
            options={
                'verbose_name': 'Survey Submission',
                'verbose_name_plural': 'Survey Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('chips', 'Chips'), ('cards', 'Cards')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('visible_when', models.JSONField(blank=True, null=True)),
                ('options_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.choicecategory')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.surveystep')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surveyquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.surveysubmission')),
            ],
        ),
        migrations.AddField(
            model_name='mandal',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='api.revenuedivision'),
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.choicecategory')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AdminInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='surveysubmission',
            index=models.Index(fields=['mobile_number', 'created_at'], name='api_surveys_mobile__dce165_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='choiceoption',
            unique_together={('category', 'code')},
        ),
    ]
