# Generated by Django 4.2.27 on 2026-01-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_code', models.CharField(max_length=20, unique=True)),
                ('village_name', models.CharField(max_length=150)),
                ('local_name', models.CharField(blank=True, max_length=150)),
                ('display_order', models.IntegerField(default=0)),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='api.mandal')),
            ],
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.village'),
        ),
    ]
