# Generated by Django 4.2.27 on 2026-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_village_surveysubmission_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
