# Generated by Django 4.2.27 on 2026-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_choiceoption_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within the step'),
        ),
    ]
